name: 'Send Email'
description: 'Send an email using a Python script.'
inputs:
  smtp_server:
    description: 'SMTP server address'
    required: true
  smtp_port:
    description: 'SMTP server port'
    required: true
  username:
    description: 'SMTP server username'
    required: true
  password:
    description: 'SMTP server password'
    required: true
  from_email:
    description: 'Email address of the sender'
    required: true
  to_email:
    description: 'Email address of the recipient'
    required: true
  attachments:
    description: 'List of file paths to attach'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
      shell: bash

    - name: Run mail script
      run: |
        python action/notification/mail.py --smtp_server="${{ inputs.smtp_server }}" --smtp_port="${{ inputs.smtp_port }}" --username="${{ inputs.username }}" --password="${{ inputs.password }}" --from_email="${{ inputs.from_email }}" --to_email="${{ inputs.to_email }}" --attachments ${{ inputs.attachments }}
      shell: bash
